sudo: false
language: node_js
node_js:
  - 8
  - 10
before_install:
  - export TZ=America/New_York
cache: yarn
install:
  - yarn --ignore-engines
branches:
  only:
  - master
  - dev
script:
  - npm run lint
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | coveralls
