import Input from '../src/input';
import Alert from '../src/alert';
import Panel from '../src/panel';
import PanelHeader from '../src/panel-header';
import PanelBody from '../src/panel-body';
import PanelFooter from '../src/panel-footer';
import Cell from '../src/cell';
import Checkbox from '../src/checkbox';
import CheckboxGroup from '../src/checkbox-group';
import Icon from '../src/icon';
import Button from '../src/button';
import Spinner from '../src/spinner';
import Message from '../src/message';
import Radio from '../src/radio';
import RadioGroup from '../src/radio-group';
import Badge from '../src/badge';
import Tabs from '../src/tabs';
import TabPane from '../src/tab-pane';
import Stepper from '../src/stepper';
import Switch from '../src/switch';
import Mask from '../src/mask';
import Toast from '../src/toast';
import Tooltip from '../src/tooltip';
import Loading from '../src/loading';
import Popup from '../src/popup';
import Uploader from '../src/uploader';
import ActionSheet from '../src/actionsheet';
import Modal from '../src/modal';
import Confirm from '../src/confirm';
import Slider from '../src/slider';
import SwipeAction from '../src/swipe-action';
import Swipe from '../src/swipe';
import SwipeItem from '../src/swipe-item';
import Picker from '../src/picker';
import Calendar from '../src/calendar';
import Colume from '../src/column';
import ColumeGroup from '../src/column-group';
import Cascader from '../src/cascader';
import Progress from '../src/progress';
import DatePicker from '../src/date-picker';
import StackPicker from '../src/stack-picker';
import NoticeBar from '../src/notice-bar';
import Drag from '../src/drag';
import Pull from '../src/pull';

export const zaInput = Input;
export const zaAlert = Alert;
export const zaPanel = Panel;
export const zaPanelHeader = PanelHeader;
export const zaPanelBody = PanelBody;
export const zaPanelFooter = PanelFooter;
export const zaCell = Cell;
export const zaCheckbox = Checkbox;
export const zaCheckboxGroup = CheckboxGroup;
export const zaIcon = Icon;
export const zaButton = Button;
export const zaSpinner = Spinner;
export const zaMessage = Message;
export const zaRadio = Radio;
export const zaRadioGroup = RadioGroup;
export const zaBadge = Badge;
export const zaTabs = Tabs;

export const zaTabPane = TabPane;
export const zaStepper = Stepper;
export const zaSlider = Slider;
export const zaSwitch = Switch;
export const zaMask = Mask;
export const zaToast = Toast;
export const zaTooltip = Tooltip;
export const zaLoading = Loading;
export const zaPopup = Popup;
export const zaUploader = Uploader;
export const zaActionSheet = ActionSheet;
export const zaModal = Modal;
export const zaConfirm = Confirm;
export const zaSwipeAction = SwipeAction;
export const zaSwipe = Swipe;

export const zaSwipeItem = SwipeItem;
export const zaPicker = Picker;
export const zaCalendar = Calendar;
export const zaColume = Colume;
export const zaColumeGroup = ColumeGroup;
export const zaCascader = Cascader;
export const zaProgress = Progress;

export const zaDatePicker = DatePicker;
export const zaStackPicker = StackPicker;
export const zaNoticeBar = NoticeBar;
export const zaDrag = Drag;
export const zaPull = Pull;
